# Generated by Django 5.0 on 2024-01-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='card_cvv',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card_holder',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='card_number',
        ),
    ]
