# Generated by Django 5.0 on 2024-01-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_remove_subscription_card_cvv_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionlist',
            options={'ordering': ['subscription_price']},
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
